// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogFile() {
  return window['go']['main']['WailsApp']['ClearLogFile']();
}

export function GetConfig() {
  return window['go']['main']['WailsApp']['GetConfig']();
}

export function GetLogFilePath() {
  return window['go']['main']['WailsApp']['GetLogFilePath']();
}

export function GetLogFileSize() {
  return window['go']['main']['WailsApp']['GetLogFileSize']();
}

export function GetMonicaCookie() {
  return window['go']['main']['WailsApp']['GetMonicaCookie']();
}

export function GetQuota() {
  return window['go']['main']['WailsApp']['GetQuota']();
}

export function GetServiceStatus() {
  return window['go']['main']['WailsApp']['GetServiceStatus']();
}

export function OpenLogDirectory() {
  return window['go']['main']['WailsApp']['OpenLogDirectory']();
}

export function StartService() {
  return window['go']['main']['WailsApp']['StartService']();
}

export function StopService() {
  return window['go']['main']['WailsApp']['StopService']();
}

export function TestConfig() {
  return window['go']['main']['WailsApp']['TestConfig']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['WailsApp']['UpdateConfig'](arg1);
}
