// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogFile():Promise<void>;

export function GetConfig():Promise<Record<string, any>>;

export function GetLogFilePath():Promise<string>;

export function GetLogFileSize():Promise<string>;

export function GetMonicaCookie():Promise<string>;

export function GetQuota():Promise<main.QuotaInfo>;

export function GetServiceStatus():Promise<main.ServiceStatus>;

export function OpenLogDirectory():Promise<void>;

export function StartService():Promise<void>;

export function StopService():Promise<void>;

export function TestConfig():Promise<Array<main.WailsTestResult>>;

export function UpdateConfig(arg1:Record<string, any>):Promise<void>;
